version: '3.3'

networks:
  bigdata:
    driver: bridge

volumes:
  mysqldata:

services:
  mysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    security_opt:
       - seccomp:unconfined
    ports:
      - "3307:3306"
    expose:
      - "3307"
    volumes:
      - ./docker/mysql/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      - mysqldata:/var/lib/mysql
    environment:
      MYSQL_DATABASE: 'sales'
      MYSQL_USER: 'bigdata'
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_PASSWORD: 'bigdata'
    networks:
      - bigdata
    healthcheck:
      test: "mysqladmin --user bigdata -pbigdata ping"
      interval: 3s
      timeout: 5s
      retries: 20

  graphite:
    image: nickstenning/graphite
    ports:
      - "8129:80" # UI
      - "2003:2003"
      - "2004:2004"
      - "7002:7002"
    expose:
      - "8129"
      - "2003"
      - "2004"
      - "7002"
    networks:
      - bigdata

  prometheus-mysql:
    image: prom/mysqld-exporter
    environment:
      DATA_SOURCE_NAME: root:root@(mysql:3306)/sales
    ports:
    - 9104:9104
    networks:
      - bigdata

  prometheus:
    image: prom/prometheus
    volumes:
    - ./docker/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
    - 9090:9090
    networks:
      - bigdata

  grafana:
    image: grafana/grafana
    ports:
      - "8130:3000" # UI
    networks:
      - bigdata
