{
 "title": "Business Dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "On Time Revenue ",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 0 },
   "format": "currencyUSD",
   "valueName": "total",
   "targets": [
    {
     "rawSql": "SELECT t.*\nFROM (SELECT\n        fulldate as \"time\",\n        sum(price * units) as \"Revenue\"\n      FROM sales_raw\n      WHERE\n        $__timeFilter(fulldate)\n      GROUP BY 1) t\n      UNION ALL SELECT now(), 0"
    }
   ]
  },
  {
   "title": "Order Method",
   "type": "graph",
   "gridPos": { "h": 6, "w": 20, "x": 4, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  fulldate AS \"time\",\n  ordermethod AS \"metric\",\n  count(*) AS \"count\"\nFROM sales_raw\nWHERE\n  $__timeFilter(fulldate)\nGROUP BY 1, 2\nORDER BY ordermethod"
    }
   ]
  },
  {
   "title": "Units Per Country",
   "type": "graph",
   "description": "Show number of sold units per country ",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(fulldate,$__interval),\n  country AS metric,\n  sum(units) AS \"units\"\nFROM sales_raw\nWHERE\n  $__timeFilter(fulldate)\nGROUP BY 1, 2\nORDER BY $__timeGroup(fulldate,$__interval)"
    }
   ]
  },
  {
   "title": "Last Orders",
   "type": "table",
   "description": "Show last few orders",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 11 },
   "targets": [
    {
     "rawSql": "SELECT * FROM sales_raw order by fulldate desc limit 5"
    }
   ]
  }
 ]
}