{
 "title": "Developer Dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "QPS/Exceptions",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "alias(perSecond(bigdata.bi.debian.com.itechart.bitools.BiServlet.request.*.*.all.count, 15), 'requests')"
    },
    {
     "target": "alias(perSecond(bigdata.bi.debian.com.itechart.bitools.BiServlet.request.*.*.exceptions.count, 15), 'exceptions')"
    }
   ]
  },
  {
   "title": "On-Time Orders  ",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(bigdata.bi.*.com.itechart.bitools.BiServlet.orders.*.*.*.m1_rate, 7, 8, 9, 10)"
    }
   ]
  },
  {
   "title": "GC Time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(perSecond(bigdata.bi.*.jvm.gc.*.time, 1), 5, 6)"
    }
   ]
  },
  {
   "title": "JVM Total",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "bits" }
   ],
   "targets": [
    {
     "target": "aliasByNode(bigdata.bi.*.jvm.memory.total.*, 6)"
    }
   ]
  },
  {
   "title": "JVM Threads",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(bigdata.bi.*.jvm.thread.state.*.count, 6, 7)"
    }
   ]
  },
  {
   "title": "JVM Heap",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(bigdata.bi.*.jvm.memory.heap.*, 6)"
    }
   ]
  }
 ]
}