{
 "title": "Graphite Carbon Metrics",
 "tags": [
  "graphite",
  "carbon"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Carbon Ops",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "alias(sumSeries(carbon.agents.*.updateOperations),\"Updates\") "
    },
    {
     "target": "alias(sumSeries(carbon.agents.*.metricsReceived),'Metrics Received')"
    },
    {
     "target": "alias(sumSeries(carbon.agents.*.committedPoints),'Committed Points')"
    },
    {
     "target": "alias(sumSeries(carbon.agents.*.creates),'Creates')"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "target": "alias(averageSeries(carbon.agents.*.cpuUsage),'CPU')"
    }
   ]
  },
  {
   "title": "Points Per Update",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "alias(averageSeries(carbon.agents.*.pointsPerUpdate), 'Points Per Update')"
    }
   ]
  }
 ]
}