# -- create user table

# --- !Ups

CREATE TABLE MARKETING_PROMOTIONS
(
	PROMOTION_ID INTEGER,
	DESCRIPTION CLOB,
	START_DATE VARCHAR(20),
	END_DATE VARCHAR(20),
	PRODUCT INTEGER,
	AREA VARCHAR(50),
	TYPE VARCHAR(50),
	DISCOUNT DOUBLE,
	CHANNEL VARCHAR(50)
);

# --- !Downs

DROP TABLE IF EXISTS MARKETING_PROMOTIONS;