# -- update start/end date of promotion

# --- !Ups

ALTER TABLE MARKETING_PROMOTIONS ALTER COLUMN START_DATE VARCHAR(40)
ALTER TABLE MARKETING_PROMOTIONS ALTER COLUMN END_DATE VARCHAR(40)

UPDATE MARKETING_PROMOTIONS
SET END_DATE = FORMATDATETIME(
        DATEADD(WEEK, 2,
            PARSEDATETIME(
                START_DATE,
                'MMM dd, yyyy hh:mm:ss','en')),
        'MMM dd, yyyy hh:mm:ss a','en');

UPDATE MARKETING_PROMOTIONS
SET START_DATE = FORMATDATETIME(
        PARSEDATETIME(
            START_DATE,
            'MMM dd, yyyy hh:mm:ss','en'),
        'MMM dd, yyyy hh:mm:ss a','en');

# --- !Downs

ALTER TABLE MARKETING_PROMOTIONS ALTER COLUMN START_DATE VARCHAR(20)
ALTER TABLE MARKETING_PROMOTIONS ALTER COLUMN END_DATE VARCHAR(20)