version: '3.3'

services:
  redis:
    build:
      context: docker/redis
    ports:
      - "6379:6379"
  restapi:
    build:
      context: docker/restapi
    depends_on:
      - redis
    ports:
      - "9000:9000"
      - "9902:9902"
      - "8802:8802"

